#!/usr/bin/env python3

"""
Generic subsystem migrator.

Copies

    ../llmTace/<subsystem>/*.py

into the current directory as

    new_<subsystem>_<file>.py

and rewrites internal imports.

Example:

    python migrate_subsystem.py compiler

"""

from pathlib import Path
import re
import shutil
import sys

# ---------------------------------------------------------

if len(sys.argv) != 2:
    print("Usage:")
    print("    python migrate_subsystem.py <subsystem>")
    sys.exit(1)

subsystem = sys.argv[1]

SOURCE = (
    Path("../llmTace")
    / subsystem
)

TARGET = Path(".")

if not SOURCE.exists():
    print(f"Source folder not found:\n{SOURCE}")
    sys.exit(1)

print("=" * 60)
print("Migrating:", subsystem)
print("=" * 60)

# ---------------------------------------------------------

files = sorted(SOURCE.glob("*.py"))

if not files:
    print("No python files.")
    sys.exit(0)

count = 0
rewrites = 0

# ---------------------------------------------------------

for src in files:

    new_name = (
        "new_"
        + subsystem
        + "_"
        + src.name
    )

    dst = TARGET / new_name

    shutil.copy2(src, dst)

    text = dst.read_text(
        encoding="utf-8"
    )

    #
    # Rewrite imports belonging
    # to THIS subsystem.
    #

    pattern = (
        rf"from\s+{re.escape(subsystem)}\."
        r"([A-Za-z0-9_]+)"
        r"\s+import"
    )

    def repl(m):

        nonlocal_rewrites[0] += 1

        return (
            "from new_"
            + subsystem
            + "_"
            + m.group(1)
            + " import"
        )

    nonlocal_rewrites = [0]

    text = re.sub(
        pattern,
        repl,
        text,
    )

    header = f'''"""
AUTO-MIGRATED

Original:
    {src}

Generated by:
    migrate_subsystem.py

Subsystem:
    {subsystem}

"""

'''

    if not text.startswith('"""AUTO-MIGRATED'):
        text = header + text

    dst.write_text(
        text,
        encoding="utf-8"
    )

    rewrites += nonlocal_rewrites[0]
    count += 1

    print(f"✓ {src.name:30} -> {new_name}")

# ---------------------------------------------------------

print()
print("=" * 60)
print("Done")
print("=" * 60)
print(f"Files copied     : {count}")
print(f"Imports rewritten: {rewrites}")
