#!/usr/bin/env python3

"""
Ontology layer.

Ontology relations preserve the canonical operator
generated by the Soar of the Logos.
"""

from dataclasses import dataclass


@dataclass(slots=True)
class OntologicalEntity:

    entity_id: int | None
    concept_id: int | None
    lexical: str


@dataclass(slots=True)
class OntologicalConcept:

    concept_id: int
    module: str
    name: str


@dataclass(slots=True)
class OntologicalRelation:

    subject: OntologicalEntity

    # Canonical operator
    operator: str

    object: OntologicalEntity


if __name__ == "__main__":

    relation = OntologicalRelation(

        subject=OntologicalEntity(
            entity_id=101,
            concept_id=10,
            lexical="John",
        ),

        operator="IS_A",

        object=OntologicalEntity(
            entity_id=202,
            concept_id=20,
            lexical="Human",
        ),

    )

    print(relation)
